// @ts-check

import { AiReviewerCommentProvenance as AiReviewerCommentProvenanceModel } from "../models/AiReviewerCommentProvenance.mjs";

export class AiReviewerCommentProvenanceValidationError extends Error {
  constructor() {
    super("The AI-assisted comment provenance identifier is invalid.");
    this.name = "AiReviewerCommentProvenanceValidationError";
  }
}

/**
 * Comment/thread identifiers are generated by RangesTracker as MongoDB
 * ObjectId-shaped values. Projects use the same identifier shape.
 *
 * @param {unknown} input
 */
function objectId(input) {
  try {
    const value = /** @type {any} */ (input)?.toString?.();
    if (typeof value !== "string" || !/^[0-9a-f]{24}$/i.test(value)) {
      throw new AiReviewerCommentProvenanceValidationError();
    }
    return value.toLowerCase();
  } catch (error) {
    if (error instanceof AiReviewerCommentProvenanceValidationError) {
      throw error;
    }
    throw new AiReviewerCommentProvenanceValidationError();
  }
}

/**
 * @param {{ model?: typeof AiReviewerCommentProvenanceModel }} [dependencies]
 */
export function createAiReviewerCommentProvenanceStore({
  model = AiReviewerCommentProvenanceModel,
} = {}) {
  return {
    /** @param {unknown} projectIdInput */
    async list(projectIdInput) {
      const projectId = objectId(projectIdInput);
      const records = await model.find({ projectId }).lean().exec();
      return records
        .map((record) => objectId(record._id))
        .sort((left, right) => left.localeCompare(right));
    },

    /**
     * @param {unknown} projectIdInput
     * @param {unknown} commentIdInput
     */
    async mark(projectIdInput, commentIdInput) {
      const projectId = objectId(projectIdInput);
      const commentId = objectId(commentIdInput);
      const result = await model
        .updateOne(
          { _id: commentId, projectId },
          {
            $setOnInsert: {
              _id: commentId,
              projectId,
            },
          },
          {
            runValidators: true,
            setDefaultsOnInsert: true,
            upsert: true,
          },
        )
        .exec();
      return {
        commentId,
        created: result.upsertedCount === 1 || result.upsertedId != null,
      };
    },

    /**
     * @param {unknown} projectIdInput
     * @param {unknown} commentIdInput
     */
    async unmark(projectIdInput, commentIdInput) {
      const projectId = objectId(projectIdInput);
      const commentId = objectId(commentIdInput);
      const result = await model
        .deleteOne({ _id: commentId, projectId })
        .exec();
      return result.deletedCount === 1;
    },

    /** @param {unknown} projectIdInput */
    async deleteProject(projectIdInput) {
      const projectId = objectId(projectIdInput);
      return await model.deleteMany({ projectId }).exec();
    },
  };
}
