// @ts-check

import { AiReviewerCommentProvenance as AiReviewerCommentProvenanceModel } from "../models/AiReviewerCommentProvenance.mjs";
import ChatApiHandler from "../../../../app/src/Features/Chat/ChatApiHandler.mjs";

export class AiReviewerCommentProvenanceValidationError extends Error {
  constructor() {
    super("The AI-assisted comment provenance identifier is invalid.");
    this.name = "AiReviewerCommentProvenanceValidationError";
  }
}

/**
 * Comment/thread identifiers are generated by RangesTracker as MongoDB
 * ObjectId-shaped values. Projects use the same identifier shape.
 *
 * @param {unknown} input
 */
function objectId(input) {
  try {
    const value = /** @type {any} */ (input)?.toString?.();
    if (typeof value !== "string" || !/^[0-9a-f]{24}$/i.test(value)) {
      throw new AiReviewerCommentProvenanceValidationError();
    }
    return value.toLowerCase();
  } catch (error) {
    if (error instanceof AiReviewerCommentProvenanceValidationError) {
      throw error;
    }
    throw new AiReviewerCommentProvenanceValidationError();
  }
}

/** @param {unknown} input */
function boundedIdentifier(input) {
  try {
    const value = /** @type {any} */ (input)?.toString?.();
    if (typeof value !== "string" || value.length === 0 || value.length > 200) {
      throw new AiReviewerCommentProvenanceValidationError();
    }
    return value;
  } catch (error) {
    if (error instanceof AiReviewerCommentProvenanceValidationError) {
      throw error;
    }
    throw new AiReviewerCommentProvenanceValidationError();
  }
}

/**
 * @param {{
 *   model?: typeof AiReviewerCommentProvenanceModel,
 *   getThreadState?: (projectId: string, commentId: string, signal: AbortSignal) => Promise<{ state: string }>
 * }} [dependencies]
 */
export function createAiReviewerCommentProvenanceStore({
  model = AiReviewerCommentProvenanceModel,
  getThreadState = ChatApiHandler.promises.getThreadState,
} = {}) {
  return {
    /**
     * @param {unknown} projectIdInput
     * @param {unknown} runIdInput
     * @param {unknown} artifactIdInput
     */
    async lookup(projectIdInput, runIdInput, artifactIdInput) {
      const projectId = objectId(projectIdInput);
      const runId = boundedIdentifier(runIdInput);
      const artifactId = boundedIdentifier(artifactIdInput);
      const record = await model
        .findOne({ projectId, runId, artifactId })
        .lean()
        .exec();
      if (record == null) {
        return null;
      }

      const commentId = objectId(record._id);
      if (record.replyThreadId != null) {
        const threadId = objectId(record.replyThreadId);
        const messageId =
          record.replyMessageId == null
            ? null
            : objectId(record.replyMessageId);
        return {
          commentId,
          confirmed: record.uncertain !== true && messageId != null,
          threadId,
          messageId,
        };
      }
      if (record.uncertain !== true) {
        return { commentId, confirmed: true };
      }

      let state;
      try {
        ({ state } = await getThreadState(
          projectId,
          commentId,
          new AbortController().signal,
        ));
      } catch {
        return { commentId, confirmed: false };
      }
      if (state === "current" || state === "resolved") {
        await model
          .updateOne(
            { _id: commentId, projectId, runId, artifactId },
            { $set: { uncertain: false } },
          )
          .exec();
        return { commentId, confirmed: true };
      }
      return { commentId, confirmed: false };
    },

    /** @param {unknown} projectIdInput */
    async list(projectIdInput) {
      const projectId = objectId(projectIdInput);
      const records = await model.find({ projectId }).lean().exec();
      const resolvedRecords = await Promise.all(
        records.map(async (record) => {
          const commentId = objectId(record._id);
          if (record.replyThreadId != null) {
            return record.uncertain !== true && record.replyMessageId != null
              ? objectId(record.replyMessageId)
              : null;
          }
          if (record.uncertain !== true) {
            return commentId;
          }
          // Resolving an unconfirmed record is opportunistic. When the chat
          // service cannot answer, keep the record unconfirmed and still list
          // it: a reconciliation failure must not fail the read itself.
          let state;
          try {
            ({ state } = await getThreadState(
              projectId,
              commentId,
              new AbortController().signal,
            ));
          } catch {
            return commentId;
          }
          if (state === "absent") {
            await model.deleteOne({ _id: commentId, projectId }).exec();
            return null;
          }
          if (state === "current" || state === "resolved") {
            await model
              .updateOne(
                { _id: commentId, projectId },
                { $set: { uncertain: false } },
              )
              .exec();
          }
          return commentId;
        }),
      );
      return resolvedRecords
        .filter((commentId) => commentId != null)
        .sort((left, right) => left.localeCompare(right));
    },

    /**
     * @param {unknown} projectIdInput
     * @param {unknown} commentIdInput
     * @param {unknown} runIdInput
     * @param {unknown} artifactIdInput
     * @param {unknown} [replyThreadIdInput]
     */
    async mark(
      projectIdInput,
      commentIdInput,
      runIdInput,
      artifactIdInput,
      replyThreadIdInput,
    ) {
      const projectId = objectId(projectIdInput);
      const commentId = objectId(commentIdInput);
      const runId = boundedIdentifier(runIdInput);
      const artifactId = boundedIdentifier(artifactIdInput);
      const replyThreadId =
        replyThreadIdInput == null ? null : objectId(replyThreadIdInput);
      let result;
      try {
        result = await model
          .updateOne(
            { projectId, runId, artifactId },
            {
              $setOnInsert: {
                _id: commentId,
                projectId,
                runId,
                artifactId,
                ...(replyThreadId == null ? {} : { replyThreadId }),
                uncertain: true,
              },
            },
            {
              runValidators: true,
              setDefaultsOnInsert: true,
              upsert: true,
            },
          )
          .exec();
      } catch (error) {
        if (/** @type {any} */ (error)?.code !== 11000) {
          throw error;
        }
      }
      const record = await model
        .findOne({ projectId, runId, artifactId })
        .lean()
        .exec();
      if (record == null) {
        throw new Error("The AI-assisted comment reservation was not found.");
      }
      const storedReplyThreadId =
        record.replyThreadId == null ? null : objectId(record.replyThreadId);
      if (storedReplyThreadId !== replyThreadId) {
        throw new AiReviewerCommentProvenanceValidationError();
      }
      return {
        commentId: objectId(record._id),
        created: result?.upsertedCount === 1 || result?.upsertedId != null,
        confirmed:
          record.uncertain !== true &&
          (replyThreadId == null || record.replyMessageId != null),
        ...(replyThreadId == null
          ? {}
          : {
              threadId: storedReplyThreadId,
              messageId:
                record.replyMessageId == null
                  ? null
                  : objectId(record.replyMessageId),
            }),
      };
    },

    /**
     * @param {unknown} projectIdInput
     * @param {unknown} commentIdInput
     * @param {unknown} runIdInput
     * @param {unknown} artifactIdInput
     * @param {unknown} replyThreadIdInput
     * @param {unknown} replyMessageIdInput
     */
    async confirmReply(
      projectIdInput,
      commentIdInput,
      runIdInput,
      artifactIdInput,
      replyThreadIdInput,
      replyMessageIdInput,
    ) {
      const projectId = objectId(projectIdInput);
      const commentId = objectId(commentIdInput);
      const runId = boundedIdentifier(runIdInput);
      const artifactId = boundedIdentifier(artifactIdInput);
      const replyThreadId = objectId(replyThreadIdInput);
      const replyMessageId = objectId(replyMessageIdInput);
      await model
        .updateOne(
          {
            _id: commentId,
            projectId,
            runId,
            artifactId,
            replyThreadId,
          },
          { $set: { replyMessageId, uncertain: false } },
        )
        .exec();
      const record = await model
        .findOne({ _id: commentId, projectId, runId, artifactId })
        .lean()
        .exec();
      if (
        record == null ||
        objectId(record.replyThreadId) !== replyThreadId ||
        objectId(record.replyMessageId) !== replyMessageId ||
        record.uncertain === true
      ) {
        throw new Error("The AI-assisted reply provenance was not confirmed.");
      }
      return {
        commentId,
        confirmed: true,
        threadId: replyThreadId,
        messageId: replyMessageId,
      };
    },

    /**
     * @param {unknown} projectIdInput
     * @param {unknown} commentIdInput
     */
    async unmark(projectIdInput, commentIdInput) {
      const projectId = objectId(projectIdInput);
      const commentId = objectId(commentIdInput);
      const result = await model
        .deleteOne({ _id: commentId, projectId })
        .exec();
      return result.deletedCount === 1;
    },

    /** @param {unknown} projectIdInput */
    async deleteProject(projectIdInput) {
      const projectId = objectId(projectIdInput);
      return await model.deleteMany({ projectId }).exec();
    },
  };
}
